# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'searchform.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QAbstractItemView, QApplication, QCheckBox,
    QComboBox, QDateEdit, QDialog, QDialogButtonBox,
    QGridLayout, QHBoxLayout, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QSizePolicy, QSpacerItem,
    QSpinBox, QTabWidget, QTimeEdit, QVBoxLayout,
    QWidget)

class Ui_searchform(object):
    def setupUi(self, searchform):
        if not searchform.objectName():
            searchform.setObjectName(u"searchform")
        searchform.resize(576, 404)
        self.horizontalLayout = QHBoxLayout(searchform)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.tabWidget = QTabWidget(searchform)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.verticalLayout_2 = QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.date_from = QDateEdit(self.tab)
        self.date_from.setObjectName(u"date_from")

        self.gridLayout.addWidget(self.date_from, 1, 1, 1, 1)

        self.price_to = QSpinBox(self.tab)
        self.price_to.setObjectName(u"price_to")
        self.price_to.setMaximum(999999999)

        self.gridLayout.addWidget(self.price_to, 5, 3, 1, 1)

        self.return_from = QDateEdit(self.tab)
        self.return_from.setObjectName(u"return_from")

        self.gridLayout.addWidget(self.return_from, 2, 1, 1, 1)

        self.label_7 = QLabel(self.tab)
        self.label_7.setObjectName(u"label_7")

        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)

        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")

        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)

        self.label_8 = QLabel(self.tab)
        self.label_8.setObjectName(u"label_8")

        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)

        self.nights_in_dst_from = QSpinBox(self.tab)
        self.nights_in_dst_from.setObjectName(u"nights_in_dst_from")

        self.gridLayout.addWidget(self.nights_in_dst_from, 3, 1, 1, 1)

        self.max_fly_duration = QSpinBox(self.tab)
        self.max_fly_duration.setObjectName(u"max_fly_duration")

        self.gridLayout.addWidget(self.max_fly_duration, 4, 1, 1, 1)

        self.date_to = QDateEdit(self.tab)
        self.date_to.setObjectName(u"date_to")

        self.gridLayout.addWidget(self.date_to, 1, 3, 1, 1)

        self.select_airlines_exclude = QCheckBox(self.tab)
        self.select_airlines_exclude.setObjectName(u"select_airlines_exclude")

        self.gridLayout.addWidget(self.select_airlines_exclude, 6, 3, 1, 1)

        self.label_9 = QLabel(self.tab)
        self.label_9.setObjectName(u"label_9")

        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)

        self.label_6 = QLabel(self.tab)
        self.label_6.setObjectName(u"label_6")

        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)

        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")

        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.select_stop_airport = QLineEdit(self.tab)
        self.select_stop_airport.setObjectName(u"select_stop_airport")

        self.gridLayout.addWidget(self.select_stop_airport, 7, 1, 1, 1)

        self.label_4 = QLabel(self.tab)
        self.label_4.setObjectName(u"label_4")

        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)

        self.label_10 = QLabel(self.tab)
        self.label_10.setObjectName(u"label_10")

        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)

        self.nights_in_dst_to = QSpinBox(self.tab)
        self.nights_in_dst_to.setObjectName(u"nights_in_dst_to")

        self.gridLayout.addWidget(self.nights_in_dst_to, 3, 3, 1, 1)

        self.return_to = QDateEdit(self.tab)
        self.return_to.setObjectName(u"return_to")

        self.gridLayout.addWidget(self.return_to, 2, 3, 1, 1)

        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")

        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)

        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")

        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)

        self.price_from = QSpinBox(self.tab)
        self.price_from.setObjectName(u"price_from")
        self.price_from.setMaximum(999999999)

        self.gridLayout.addWidget(self.price_from, 5, 1, 1, 1)

        self.fly_to = QLineEdit(self.tab)
        self.fly_to.setObjectName(u"fly_to")

        self.gridLayout.addWidget(self.fly_to, 0, 3, 1, 1)

        self.select_stop_airport_exclude = QCheckBox(self.tab)
        self.select_stop_airport_exclude.setObjectName(u"select_stop_airport_exclude")

        self.gridLayout.addWidget(self.select_stop_airport_exclude, 7, 3, 1, 1)

        self.label_11 = QLabel(self.tab)
        self.label_11.setObjectName(u"label_11")

        self.gridLayout.addWidget(self.label_11, 5, 2, 1, 1)

        self.select_airlines = QLineEdit(self.tab)
        self.select_airlines.setObjectName(u"select_airlines")

        self.gridLayout.addWidget(self.select_airlines, 6, 1, 1, 1)

        self.label_12 = QLabel(self.tab)
        self.label_12.setObjectName(u"label_12")

        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)

        self.fly_from = QLineEdit(self.tab)
        self.fly_from.setObjectName(u"fly_from")

        self.gridLayout.addWidget(self.fly_from, 0, 1, 1, 1)

        self.label_13 = QLabel(self.tab)
        self.label_13.setObjectName(u"label_13")

        self.gridLayout.addWidget(self.label_13, 7, 0, 1, 1)


        self.verticalLayout_2.addLayout(self.gridLayout)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer_2)

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.verticalLayout = QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.adults = QSpinBox(self.tab_2)
        self.adults.setObjectName(u"adults")
        self.adults.setValue(1)

        self.gridLayout_2.addWidget(self.adults, 0, 1, 1, 1)

        self.adult_hand_bag = QLineEdit(self.tab_2)
        self.adult_hand_bag.setObjectName(u"adult_hand_bag")

        self.gridLayout_2.addWidget(self.adult_hand_bag, 2, 3, 1, 1)

        self.label_20 = QLabel(self.tab_2)
        self.label_20.setObjectName(u"label_20")

        self.gridLayout_2.addWidget(self.label_20, 3, 0, 1, 1)

        self.adult_hold_bag = QLineEdit(self.tab_2)
        self.adult_hold_bag.setObjectName(u"adult_hold_bag")

        self.gridLayout_2.addWidget(self.adult_hold_bag, 2, 1, 1, 1)

        self.label_15 = QLabel(self.tab_2)
        self.label_15.setObjectName(u"label_15")

        self.gridLayout_2.addWidget(self.label_15, 0, 2, 1, 1)

        self.label_14 = QLabel(self.tab_2)
        self.label_14.setObjectName(u"label_14")

        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)

        self.child_hold_bag = QLineEdit(self.tab_2)
        self.child_hold_bag.setObjectName(u"child_hold_bag")

        self.gridLayout_2.addWidget(self.child_hold_bag, 3, 1, 1, 1)

        self.child_hand_bag = QLineEdit(self.tab_2)
        self.child_hand_bag.setObjectName(u"child_hand_bag")

        self.gridLayout_2.addWidget(self.child_hand_bag, 3, 3, 1, 1)

        self.label_16 = QLabel(self.tab_2)
        self.label_16.setObjectName(u"label_16")

        self.gridLayout_2.addWidget(self.label_16, 1, 0, 1, 1)

        self.infants = QSpinBox(self.tab_2)
        self.infants.setObjectName(u"infants")

        self.gridLayout_2.addWidget(self.infants, 1, 1, 1, 1)

        self.label_17 = QLabel(self.tab_2)
        self.label_17.setObjectName(u"label_17")

        self.gridLayout_2.addWidget(self.label_17, 2, 0, 1, 1)

        self.children = QSpinBox(self.tab_2)
        self.children.setObjectName(u"children")

        self.gridLayout_2.addWidget(self.children, 0, 3, 1, 1)

        self.label_19 = QLabel(self.tab_2)
        self.label_19.setObjectName(u"label_19")

        self.gridLayout_2.addWidget(self.label_19, 3, 2, 1, 1)

        self.label_18 = QLabel(self.tab_2)
        self.label_18.setObjectName(u"label_18")

        self.gridLayout_2.addWidget(self.label_18, 2, 2, 1, 1)

        self.label_21 = QLabel(self.tab_2)
        self.label_21.setObjectName(u"label_21")

        self.gridLayout_2.addWidget(self.label_21, 4, 0, 1, 1)

        self.selected_cabins = QComboBox(self.tab_2)
        self.selected_cabins.addItem("")
        self.selected_cabins.addItem("")
        self.selected_cabins.addItem("")
        self.selected_cabins.addItem("")
        self.selected_cabins.addItem("")
        self.selected_cabins.setObjectName(u"selected_cabins")

        self.gridLayout_2.addWidget(self.selected_cabins, 4, 1, 1, 1)

        self.label_22 = QLabel(self.tab_2)
        self.label_22.setObjectName(u"label_22")

        self.gridLayout_2.addWidget(self.label_22, 4, 2, 1, 1)

        self.mix_with_cabins = QComboBox(self.tab_2)
        self.mix_with_cabins.addItem("")
        self.mix_with_cabins.addItem("")
        self.mix_with_cabins.addItem("")
        self.mix_with_cabins.addItem("")
        self.mix_with_cabins.addItem("")
        self.mix_with_cabins.setObjectName(u"mix_with_cabins")

        self.gridLayout_2.addWidget(self.mix_with_cabins, 4, 3, 1, 1)


        self.verticalLayout.addLayout(self.gridLayout_2)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.verticalLayout_3 = QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.gridLayout_3 = QGridLayout()
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.label_23 = QLabel(self.tab_3)
        self.label_23.setObjectName(u"label_23")

        self.gridLayout_3.addWidget(self.label_23, 0, 0, 1, 1)

        self.fly_days = QListWidget(self.tab_3)
        QListWidgetItem(self.fly_days)
        QListWidgetItem(self.fly_days)
        QListWidgetItem(self.fly_days)
        QListWidgetItem(self.fly_days)
        QListWidgetItem(self.fly_days)
        QListWidgetItem(self.fly_days)
        QListWidgetItem(self.fly_days)
        self.fly_days.setObjectName(u"fly_days")
        self.fly_days.setSelectionMode(QAbstractItemView.MultiSelection)
        self.fly_days.setSelectionRectVisible(True)

        self.gridLayout_3.addWidget(self.fly_days, 0, 1, 1, 1)

        self.label_26 = QLabel(self.tab_3)
        self.label_26.setObjectName(u"label_26")

        self.gridLayout_3.addWidget(self.label_26, 0, 2, 1, 1)

        self.ret_fly_days = QListWidget(self.tab_3)
        QListWidgetItem(self.ret_fly_days)
        QListWidgetItem(self.ret_fly_days)
        QListWidgetItem(self.ret_fly_days)
        QListWidgetItem(self.ret_fly_days)
        QListWidgetItem(self.ret_fly_days)
        QListWidgetItem(self.ret_fly_days)
        QListWidgetItem(self.ret_fly_days)
        self.ret_fly_days.setObjectName(u"ret_fly_days")
        self.ret_fly_days.setSelectionMode(QAbstractItemView.MultiSelection)

        self.gridLayout_3.addWidget(self.ret_fly_days, 0, 3, 1, 1)

        self.label_24 = QLabel(self.tab_3)
        self.label_24.setObjectName(u"label_24")

        self.gridLayout_3.addWidget(self.label_24, 1, 0, 1, 1)

        self.fly_days_type = QComboBox(self.tab_3)
        self.fly_days_type.addItem("")
        self.fly_days_type.addItem("")
        self.fly_days_type.addItem("")
        self.fly_days_type.setObjectName(u"fly_days_type")

        self.gridLayout_3.addWidget(self.fly_days_type, 1, 1, 1, 1)

        self.label_25 = QLabel(self.tab_3)
        self.label_25.setObjectName(u"label_25")

        self.gridLayout_3.addWidget(self.label_25, 1, 2, 1, 1)

        self.ret_fly_days_type = QComboBox(self.tab_3)
        self.ret_fly_days_type.addItem("")
        self.ret_fly_days_type.addItem("")
        self.ret_fly_days_type.addItem("")
        self.ret_fly_days_type.setObjectName(u"ret_fly_days_type")

        self.gridLayout_3.addWidget(self.ret_fly_days_type, 1, 3, 1, 1)

        self.label_27 = QLabel(self.tab_3)
        self.label_27.setObjectName(u"label_27")

        self.gridLayout_3.addWidget(self.label_27, 2, 0, 1, 1)

        self.dtime_from = QComboBox(self.tab_3)
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.addItem("")
        self.dtime_from.setObjectName(u"dtime_from")

        self.gridLayout_3.addWidget(self.dtime_from, 2, 1, 1, 1)

        self.label_28 = QLabel(self.tab_3)
        self.label_28.setObjectName(u"label_28")

        self.gridLayout_3.addWidget(self.label_28, 2, 2, 1, 1)

        self.dtime_to = QComboBox(self.tab_3)
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.addItem("")
        self.dtime_to.setObjectName(u"dtime_to")

        self.gridLayout_3.addWidget(self.dtime_to, 2, 3, 1, 1)

        self.label_29 = QLabel(self.tab_3)
        self.label_29.setObjectName(u"label_29")

        self.gridLayout_3.addWidget(self.label_29, 3, 0, 1, 1)

        self.atime_from = QComboBox(self.tab_3)
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.addItem("")
        self.atime_from.setObjectName(u"atime_from")

        self.gridLayout_3.addWidget(self.atime_from, 3, 1, 1, 1)

        self.label_30 = QLabel(self.tab_3)
        self.label_30.setObjectName(u"label_30")

        self.gridLayout_3.addWidget(self.label_30, 3, 2, 1, 1)

        self.atime_to = QComboBox(self.tab_3)
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.addItem("")
        self.atime_to.setObjectName(u"atime_to")

        self.gridLayout_3.addWidget(self.atime_to, 3, 3, 1, 1)

        self.label_32 = QLabel(self.tab_3)
        self.label_32.setObjectName(u"label_32")

        self.gridLayout_3.addWidget(self.label_32, 4, 0, 1, 1)

        self.ret_dtime_from = QComboBox(self.tab_3)
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.addItem("")
        self.ret_dtime_from.setObjectName(u"ret_dtime_from")

        self.gridLayout_3.addWidget(self.ret_dtime_from, 4, 1, 1, 1)

        self.label_31 = QLabel(self.tab_3)
        self.label_31.setObjectName(u"label_31")

        self.gridLayout_3.addWidget(self.label_31, 4, 2, 1, 1)

        self.ret_dtime_to = QComboBox(self.tab_3)
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.addItem("")
        self.ret_dtime_to.setObjectName(u"ret_dtime_to")

        self.gridLayout_3.addWidget(self.ret_dtime_to, 4, 3, 1, 1)

        self.label_33 = QLabel(self.tab_3)
        self.label_33.setObjectName(u"label_33")

        self.gridLayout_3.addWidget(self.label_33, 5, 0, 1, 1)

        self.ret_atime_from = QComboBox(self.tab_3)
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.addItem("")
        self.ret_atime_from.setObjectName(u"ret_atime_from")

        self.gridLayout_3.addWidget(self.ret_atime_from, 5, 1, 1, 1)

        self.label_34 = QLabel(self.tab_3)
        self.label_34.setObjectName(u"label_34")

        self.gridLayout_3.addWidget(self.label_34, 5, 2, 1, 1)

        self.ret_atime_to = QComboBox(self.tab_3)
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.addItem("")
        self.ret_atime_to.setObjectName(u"ret_atime_to")

        self.gridLayout_3.addWidget(self.ret_atime_to, 5, 3, 1, 1)

        self.label_35 = QLabel(self.tab_3)
        self.label_35.setObjectName(u"label_35")

        self.gridLayout_3.addWidget(self.label_35, 6, 0, 1, 1)

        self.stopover_from = QTimeEdit(self.tab_3)
        self.stopover_from.setObjectName(u"stopover_from")

        self.gridLayout_3.addWidget(self.stopover_from, 6, 1, 1, 1)

        self.label_36 = QLabel(self.tab_3)
        self.label_36.setObjectName(u"label_36")

        self.gridLayout_3.addWidget(self.label_36, 6, 2, 1, 1)

        self.stopover_to = QTimeEdit(self.tab_3)
        self.stopover_to.setObjectName(u"stopover_to")

        self.gridLayout_3.addWidget(self.stopover_to, 6, 3, 1, 1)

        self.label_37 = QLabel(self.tab_3)
        self.label_37.setObjectName(u"label_37")

        self.gridLayout_3.addWidget(self.label_37, 7, 0, 1, 1)

        self.max_stopovers = QSpinBox(self.tab_3)
        self.max_stopovers.setObjectName(u"max_stopovers")

        self.gridLayout_3.addWidget(self.max_stopovers, 7, 1, 1, 1)

        self.label_38 = QLabel(self.tab_3)
        self.label_38.setObjectName(u"label_38")

        self.gridLayout_3.addWidget(self.label_38, 7, 2, 1, 1)

        self.max_sector_stopovers = QSpinBox(self.tab_3)
        self.max_sector_stopovers.setObjectName(u"max_sector_stopovers")

        self.gridLayout_3.addWidget(self.max_sector_stopovers, 7, 3, 1, 1)


        self.verticalLayout_3.addLayout(self.gridLayout_3)

        self.verticalSpacer_3 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_3.addItem(self.verticalSpacer_3)

        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.verticalLayout_4 = QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.gridLayout_4 = QGridLayout()
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.label_39 = QLabel(self.tab_4)
        self.label_39.setObjectName(u"label_39")

        self.gridLayout_4.addWidget(self.label_39, 0, 0, 1, 1)

        self.currency = QComboBox(self.tab_4)
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.addItem("")
        self.currency.setObjectName(u"currency")

        self.gridLayout_4.addWidget(self.currency, 0, 1, 1, 1)

        self.label_40 = QLabel(self.tab_4)
        self.label_40.setObjectName(u"label_40")

        self.gridLayout_4.addWidget(self.label_40, 0, 2, 1, 1)

        self.locale = QComboBox(self.tab_4)
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.addItem("")
        self.locale.setObjectName(u"locale")

        self.gridLayout_4.addWidget(self.locale, 0, 3, 1, 1)

        self.label_41 = QLabel(self.tab_4)
        self.label_41.setObjectName(u"label_41")

        self.gridLayout_4.addWidget(self.label_41, 1, 0, 1, 1)

        self.partner_market = QLineEdit(self.tab_4)
        self.partner_market.setObjectName(u"partner_market")

        self.gridLayout_4.addWidget(self.partner_market, 1, 1, 1, 1)

        self.label_42 = QLabel(self.tab_4)
        self.label_42.setObjectName(u"label_42")

        self.gridLayout_4.addWidget(self.label_42, 1, 2, 1, 1)

        self.vehicle_type = QComboBox(self.tab_4)
        self.vehicle_type.addItem("")
        self.vehicle_type.addItem("")
        self.vehicle_type.addItem("")
        self.vehicle_type.addItem("")
        self.vehicle_type.setObjectName(u"vehicle_type")

        self.gridLayout_4.addWidget(self.vehicle_type, 1, 3, 1, 1)


        self.verticalLayout_4.addLayout(self.gridLayout_4)

        self.gridLayout_5 = QGridLayout()
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.conn_on_diff_airport = QCheckBox(self.tab_4)
        self.conn_on_diff_airport.setObjectName(u"conn_on_diff_airport")
        self.conn_on_diff_airport.setTristate(True)

        self.gridLayout_5.addWidget(self.conn_on_diff_airport, 3, 0, 1, 1)

        self.ret_to_diff_city = QCheckBox(self.tab_4)
        self.ret_to_diff_city.setObjectName(u"ret_to_diff_city")
        self.ret_to_diff_city.setTristate(True)

        self.gridLayout_5.addWidget(self.ret_to_diff_city, 0, 1, 1, 1)

        self.one_per_date = QCheckBox(self.tab_4)
        self.one_per_date.setObjectName(u"one_per_date")
        self.one_per_date.setTristate(True)

        self.gridLayout_5.addWidget(self.one_per_date, 1, 1, 1, 1)

        self.ret_from_diff_airport = QCheckBox(self.tab_4)
        self.ret_from_diff_airport.setObjectName(u"ret_from_diff_airport")
        self.ret_from_diff_airport.setTristate(True)

        self.gridLayout_5.addWidget(self.ret_from_diff_airport, 4, 0, 1, 1)

        self.ret_from_diff_city = QCheckBox(self.tab_4)
        self.ret_from_diff_city.setObjectName(u"ret_from_diff_city")
        self.ret_from_diff_city.setFocusPolicy(Qt.WheelFocus)
        self.ret_from_diff_city.setToolTipDuration(12)
        self.ret_from_diff_city.setAutoRepeatInterval(99)
        self.ret_from_diff_city.setTristate(True)

        self.gridLayout_5.addWidget(self.ret_from_diff_city, 0, 0, 1, 1)

        self.ret_to_diff_airport = QCheckBox(self.tab_4)
        self.ret_to_diff_airport.setObjectName(u"ret_to_diff_airport")
        self.ret_to_diff_airport.setTristate(True)

        self.gridLayout_5.addWidget(self.ret_to_diff_airport, 4, 1, 1, 1)

        self.enable_vi = QCheckBox(self.tab_4)
        self.enable_vi.setObjectName(u"enable_vi")
        self.enable_vi.setTristate(True)

        self.gridLayout_5.addWidget(self.enable_vi, 5, 0, 1, 1)

        self.one_for_city = QCheckBox(self.tab_4)
        self.one_for_city.setObjectName(u"one_for_city")
        self.one_for_city.setTristate(True)

        self.gridLayout_5.addWidget(self.one_for_city, 1, 0, 1, 1)

        self.only_weekends = QCheckBox(self.tab_4)
        self.only_weekends.setObjectName(u"only_weekends")
        self.only_weekends.setTristate(True)

        self.gridLayout_5.addWidget(self.only_weekends, 2, 1, 1, 1)

        self.only_working_days = QCheckBox(self.tab_4)
        self.only_working_days.setObjectName(u"only_working_days")
        self.only_working_days.setTristate(True)

        self.gridLayout_5.addWidget(self.only_working_days, 2, 0, 1, 1)


        self.verticalLayout_4.addLayout(self.gridLayout_5)

        self.verticalSpacer_4 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_4.addItem(self.verticalSpacer_4)

        self.tabWidget.addTab(self.tab_4, "")

        self.horizontalLayout.addWidget(self.tabWidget)

        self.buttonBox = QDialogButtonBox(searchform)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setOrientation(Qt.Vertical)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)

        self.horizontalLayout.addWidget(self.buttonBox)

#if QT_CONFIG(shortcut)
        self.label_7.setBuddy(self.nights_in_dst_from)
        self.label_5.setBuddy(self.return_to)
        self.label_8.setBuddy(self.nights_in_dst_to)
        self.label_9.setBuddy(self.max_fly_duration)
        self.label_6.setBuddy(self.return_from)
        self.label.setBuddy(self.fly_from)
        self.label_4.setBuddy(self.date_to)
        self.label_10.setBuddy(self.price_from)
        self.label_3.setBuddy(self.date_from)
        self.label_2.setBuddy(self.fly_to)
        self.label_11.setBuddy(self.price_to)
        self.label_12.setBuddy(self.select_airlines)
        self.label_13.setBuddy(self.select_stop_airport)
        self.label_20.setBuddy(self.child_hold_bag)
        self.label_15.setBuddy(self.children)
        self.label_14.setBuddy(self.adults)
        self.label_16.setBuddy(self.infants)
        self.label_17.setBuddy(self.adult_hold_bag)
        self.label_19.setBuddy(self.child_hand_bag)
        self.label_18.setBuddy(self.adult_hand_bag)
        self.label_21.setBuddy(self.selected_cabins)
        self.label_22.setBuddy(self.mix_with_cabins)
        self.label_23.setBuddy(self.fly_days)
        self.label_26.setBuddy(self.ret_fly_days)
        self.label_24.setBuddy(self.fly_days_type)
        self.label_25.setBuddy(self.ret_fly_days_type)
        self.label_27.setBuddy(self.dtime_from)
        self.label_28.setBuddy(self.dtime_to)
        self.label_29.setBuddy(self.atime_from)
        self.label_30.setBuddy(self.atime_to)
        self.label_32.setBuddy(self.ret_dtime_from)
        self.label_31.setBuddy(self.ret_dtime_to)
        self.label_33.setBuddy(self.ret_atime_from)
        self.label_34.setBuddy(self.ret_atime_to)
        self.label_35.setBuddy(self.stopover_from)
        self.label_36.setBuddy(self.stopover_to)
        self.label_37.setBuddy(self.max_stopovers)
        self.label_38.setBuddy(self.max_sector_stopovers)
#endif // QT_CONFIG(shortcut)
        QWidget.setTabOrder(self.fly_from, self.fly_to)
        QWidget.setTabOrder(self.fly_to, self.date_from)
        QWidget.setTabOrder(self.date_from, self.date_to)
        QWidget.setTabOrder(self.date_to, self.return_from)
        QWidget.setTabOrder(self.return_from, self.return_to)
        QWidget.setTabOrder(self.return_to, self.nights_in_dst_from)
        QWidget.setTabOrder(self.nights_in_dst_from, self.nights_in_dst_to)
        QWidget.setTabOrder(self.nights_in_dst_to, self.max_fly_duration)
        QWidget.setTabOrder(self.max_fly_duration, self.price_from)
        QWidget.setTabOrder(self.price_from, self.price_to)
        QWidget.setTabOrder(self.price_to, self.select_airlines)
        QWidget.setTabOrder(self.select_airlines, self.select_airlines_exclude)
        QWidget.setTabOrder(self.select_airlines_exclude, self.select_stop_airport)
        QWidget.setTabOrder(self.select_stop_airport, self.select_stop_airport_exclude)
        QWidget.setTabOrder(self.select_stop_airport_exclude, self.adults)
        QWidget.setTabOrder(self.adults, self.children)
        QWidget.setTabOrder(self.children, self.infants)
        QWidget.setTabOrder(self.infants, self.adult_hold_bag)
        QWidget.setTabOrder(self.adult_hold_bag, self.adult_hand_bag)
        QWidget.setTabOrder(self.adult_hand_bag, self.child_hold_bag)
        QWidget.setTabOrder(self.child_hold_bag, self.child_hand_bag)
        QWidget.setTabOrder(self.child_hand_bag, self.selected_cabins)
        QWidget.setTabOrder(self.selected_cabins, self.mix_with_cabins)
        QWidget.setTabOrder(self.mix_with_cabins, self.fly_days_type)
        QWidget.setTabOrder(self.fly_days_type, self.ret_fly_days_type)
        QWidget.setTabOrder(self.ret_fly_days_type, self.dtime_from)
        QWidget.setTabOrder(self.dtime_from, self.dtime_to)
        QWidget.setTabOrder(self.dtime_to, self.atime_from)
        QWidget.setTabOrder(self.atime_from, self.atime_to)
        QWidget.setTabOrder(self.atime_to, self.ret_dtime_from)
        QWidget.setTabOrder(self.ret_dtime_from, self.ret_dtime_to)
        QWidget.setTabOrder(self.ret_dtime_to, self.ret_atime_from)
        QWidget.setTabOrder(self.ret_atime_from, self.ret_atime_to)
        QWidget.setTabOrder(self.ret_atime_to, self.stopover_from)
        QWidget.setTabOrder(self.stopover_from, self.stopover_to)
        QWidget.setTabOrder(self.stopover_to, self.max_stopovers)
        QWidget.setTabOrder(self.max_stopovers, self.max_sector_stopovers)

        self.retranslateUi(searchform)

        self.tabWidget.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(searchform)
    # setupUi

    def retranslateUi(self, searchform):
        searchform.setWindowTitle(QCoreApplication.translate("searchform", u"Dialog", None))
        self.label_7.setText(QCoreApplication.translate("searchform", u"Nights in dst from:", None))
        self.label_5.setText(QCoreApplication.translate("searchform", u"Return to:", None))
        self.label_8.setText(QCoreApplication.translate("searchform", u"Nights in dst to:", None))
        self.select_airlines_exclude.setText(QCoreApplication.translate("searchform", u"Select airlines exclude", None))
        self.label_9.setText(QCoreApplication.translate("searchform", u"Max fly duration:", None))
        self.label_6.setText(QCoreApplication.translate("searchform", u"Return from:", None))
#if QT_CONFIG(tooltip)
        self.label.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label.setText(QCoreApplication.translate("searchform", u"Fly from *:", None))
        self.label_4.setText(QCoreApplication.translate("searchform", u"Date to *:", None))
        self.label_10.setText(QCoreApplication.translate("searchform", u"Price from:", None))
        self.nights_in_dst_to.setSpecialValueText("")
        self.label_3.setText(QCoreApplication.translate("searchform", u"Date from *:", None))
        self.label_2.setText(QCoreApplication.translate("searchform", u"Fly to:", None))
        self.select_stop_airport_exclude.setText(QCoreApplication.translate("searchform", u"Select stop airport exclude", None))
        self.label_11.setText(QCoreApplication.translate("searchform", u"Price to:", None))
        self.label_12.setText(QCoreApplication.translate("searchform", u"Select_airlines:", None))
        self.label_13.setText(QCoreApplication.translate("searchform", u"Select stop airport", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("searchform", u"Fly data", None))
        self.label_20.setText(QCoreApplication.translate("searchform", u"Child hold bag:", None))
        self.label_15.setText(QCoreApplication.translate("searchform", u"Children:", None))
        self.label_14.setText(QCoreApplication.translate("searchform", u"Adults:", None))
        self.label_16.setText(QCoreApplication.translate("searchform", u"Infants:", None))
        self.label_17.setText(QCoreApplication.translate("searchform", u"Adult hold bag:", None))
        self.label_19.setText(QCoreApplication.translate("searchform", u"Child hand bag:", None))
        self.label_18.setText(QCoreApplication.translate("searchform", u"Adult hand bag:", None))
        self.label_21.setText(QCoreApplication.translate("searchform", u"Selected cabins:", None))
        self.selected_cabins.setItemText(0, "")
        self.selected_cabins.setItemText(1, QCoreApplication.translate("searchform", u"Economy", None))
        self.selected_cabins.setItemText(2, QCoreApplication.translate("searchform", u"Economy premium", None))
        self.selected_cabins.setItemText(3, QCoreApplication.translate("searchform", u"Business", None))
        self.selected_cabins.setItemText(4, QCoreApplication.translate("searchform", u"First class", None))

        self.label_22.setText(QCoreApplication.translate("searchform", u"Mix with cabins", None))
        self.mix_with_cabins.setItemText(0, "")
        self.mix_with_cabins.setItemText(1, QCoreApplication.translate("searchform", u"Economy", None))
        self.mix_with_cabins.setItemText(2, QCoreApplication.translate("searchform", u"Economy premium", None))
        self.mix_with_cabins.setItemText(3, QCoreApplication.translate("searchform", u"Business", None))
        self.mix_with_cabins.setItemText(4, QCoreApplication.translate("searchform", u"First class", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("searchform", u"Passangers and luggages", None))
        self.label_23.setText(QCoreApplication.translate("searchform", u"Fly days:", None))

        __sortingEnabled = self.fly_days.isSortingEnabled()
        self.fly_days.setSortingEnabled(False)
        ___qlistwidgetitem = self.fly_days.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("searchform", u"Sunday", None));
        ___qlistwidgetitem1 = self.fly_days.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("searchform", u"Monday", None));
        ___qlistwidgetitem2 = self.fly_days.item(2)
        ___qlistwidgetitem2.setText(QCoreApplication.translate("searchform", u"Tuesday", None));
        ___qlistwidgetitem3 = self.fly_days.item(3)
        ___qlistwidgetitem3.setText(QCoreApplication.translate("searchform", u"Wednesday", None));
        ___qlistwidgetitem4 = self.fly_days.item(4)
        ___qlistwidgetitem4.setText(QCoreApplication.translate("searchform", u"Thursday", None));
        ___qlistwidgetitem5 = self.fly_days.item(5)
        ___qlistwidgetitem5.setText(QCoreApplication.translate("searchform", u"Friday", None));
        ___qlistwidgetitem6 = self.fly_days.item(6)
        ___qlistwidgetitem6.setText(QCoreApplication.translate("searchform", u"Saturday", None));
        self.fly_days.setSortingEnabled(__sortingEnabled)

        self.label_26.setText(QCoreApplication.translate("searchform", u"Ret fly days:", None))

        __sortingEnabled1 = self.ret_fly_days.isSortingEnabled()
        self.ret_fly_days.setSortingEnabled(False)
        ___qlistwidgetitem7 = self.ret_fly_days.item(0)
        ___qlistwidgetitem7.setText(QCoreApplication.translate("searchform", u"Sunday", None));
        ___qlistwidgetitem8 = self.ret_fly_days.item(1)
        ___qlistwidgetitem8.setText(QCoreApplication.translate("searchform", u"Monday", None));
        ___qlistwidgetitem9 = self.ret_fly_days.item(2)
        ___qlistwidgetitem9.setText(QCoreApplication.translate("searchform", u"Tuesday", None));
        ___qlistwidgetitem10 = self.ret_fly_days.item(3)
        ___qlistwidgetitem10.setText(QCoreApplication.translate("searchform", u"Wednesday", None));
        ___qlistwidgetitem11 = self.ret_fly_days.item(4)
        ___qlistwidgetitem11.setText(QCoreApplication.translate("searchform", u"Thursday", None));
        ___qlistwidgetitem12 = self.ret_fly_days.item(5)
        ___qlistwidgetitem12.setText(QCoreApplication.translate("searchform", u"Friday", None));
        ___qlistwidgetitem13 = self.ret_fly_days.item(6)
        ___qlistwidgetitem13.setText(QCoreApplication.translate("searchform", u"Saturday", None));
        self.ret_fly_days.setSortingEnabled(__sortingEnabled1)

        self.label_24.setText(QCoreApplication.translate("searchform", u"Fly days type:", None))
        self.fly_days_type.setItemText(0, "")
        self.fly_days_type.setItemText(1, QCoreApplication.translate("searchform", u"departure", None))
        self.fly_days_type.setItemText(2, QCoreApplication.translate("searchform", u"arrival", None))

        self.label_25.setText(QCoreApplication.translate("searchform", u"Ret fly days type:", None))
        self.ret_fly_days_type.setItemText(0, "")
        self.ret_fly_days_type.setItemText(1, QCoreApplication.translate("searchform", u"departure", None))
        self.ret_fly_days_type.setItemText(2, QCoreApplication.translate("searchform", u"arrival", None))

        self.label_27.setText(QCoreApplication.translate("searchform", u"Dep. time from:", None))
        self.dtime_from.setItemText(0, "")
        self.dtime_from.setItemText(1, QCoreApplication.translate("searchform", u"00:00", None))
        self.dtime_from.setItemText(2, QCoreApplication.translate("searchform", u"01:00", None))
        self.dtime_from.setItemText(3, QCoreApplication.translate("searchform", u"02:00", None))
        self.dtime_from.setItemText(4, QCoreApplication.translate("searchform", u"03:00", None))
        self.dtime_from.setItemText(5, QCoreApplication.translate("searchform", u"04:00", None))
        self.dtime_from.setItemText(6, QCoreApplication.translate("searchform", u"05:00", None))
        self.dtime_from.setItemText(7, QCoreApplication.translate("searchform", u"06:00", None))
        self.dtime_from.setItemText(8, QCoreApplication.translate("searchform", u"07:00", None))
        self.dtime_from.setItemText(9, QCoreApplication.translate("searchform", u"08:00", None))
        self.dtime_from.setItemText(10, QCoreApplication.translate("searchform", u"09:00", None))
        self.dtime_from.setItemText(11, QCoreApplication.translate("searchform", u"10:00", None))
        self.dtime_from.setItemText(12, QCoreApplication.translate("searchform", u"11:00", None))
        self.dtime_from.setItemText(13, QCoreApplication.translate("searchform", u"12:00", None))
        self.dtime_from.setItemText(14, QCoreApplication.translate("searchform", u"13:00", None))
        self.dtime_from.setItemText(15, QCoreApplication.translate("searchform", u"14:00", None))
        self.dtime_from.setItemText(16, QCoreApplication.translate("searchform", u"15:00", None))
        self.dtime_from.setItemText(17, QCoreApplication.translate("searchform", u"16:00", None))
        self.dtime_from.setItemText(18, QCoreApplication.translate("searchform", u"17:00", None))
        self.dtime_from.setItemText(19, QCoreApplication.translate("searchform", u"18:00", None))
        self.dtime_from.setItemText(20, QCoreApplication.translate("searchform", u"19:00", None))
        self.dtime_from.setItemText(21, QCoreApplication.translate("searchform", u"20:00", None))
        self.dtime_from.setItemText(22, QCoreApplication.translate("searchform", u"21:00", None))
        self.dtime_from.setItemText(23, QCoreApplication.translate("searchform", u"22:00", None))
        self.dtime_from.setItemText(24, QCoreApplication.translate("searchform", u"23:00", None))
        self.dtime_from.setItemText(25, QCoreApplication.translate("searchform", u"24:00", None))

        self.label_28.setText(QCoreApplication.translate("searchform", u"Dep. time to:", None))
        self.dtime_to.setItemText(0, "")
        self.dtime_to.setItemText(1, QCoreApplication.translate("searchform", u"00:00", None))
        self.dtime_to.setItemText(2, QCoreApplication.translate("searchform", u"01:00", None))
        self.dtime_to.setItemText(3, QCoreApplication.translate("searchform", u"02:00", None))
        self.dtime_to.setItemText(4, QCoreApplication.translate("searchform", u"03:00", None))
        self.dtime_to.setItemText(5, QCoreApplication.translate("searchform", u"04:00", None))
        self.dtime_to.setItemText(6, QCoreApplication.translate("searchform", u"05:00", None))
        self.dtime_to.setItemText(7, QCoreApplication.translate("searchform", u"06:00", None))
        self.dtime_to.setItemText(8, QCoreApplication.translate("searchform", u"07:00", None))
        self.dtime_to.setItemText(9, QCoreApplication.translate("searchform", u"08:00", None))
        self.dtime_to.setItemText(10, QCoreApplication.translate("searchform", u"09:00", None))
        self.dtime_to.setItemText(11, QCoreApplication.translate("searchform", u"10:00", None))
        self.dtime_to.setItemText(12, QCoreApplication.translate("searchform", u"11:00", None))
        self.dtime_to.setItemText(13, QCoreApplication.translate("searchform", u"12:00", None))
        self.dtime_to.setItemText(14, QCoreApplication.translate("searchform", u"13:00", None))
        self.dtime_to.setItemText(15, QCoreApplication.translate("searchform", u"14:00", None))
        self.dtime_to.setItemText(16, QCoreApplication.translate("searchform", u"15:00", None))
        self.dtime_to.setItemText(17, QCoreApplication.translate("searchform", u"16:00", None))
        self.dtime_to.setItemText(18, QCoreApplication.translate("searchform", u"17:00", None))
        self.dtime_to.setItemText(19, QCoreApplication.translate("searchform", u"18:00", None))
        self.dtime_to.setItemText(20, QCoreApplication.translate("searchform", u"19:00", None))
        self.dtime_to.setItemText(21, QCoreApplication.translate("searchform", u"20:00", None))
        self.dtime_to.setItemText(22, QCoreApplication.translate("searchform", u"21:00", None))
        self.dtime_to.setItemText(23, QCoreApplication.translate("searchform", u"22:00", None))
        self.dtime_to.setItemText(24, QCoreApplication.translate("searchform", u"23:00", None))
        self.dtime_to.setItemText(25, QCoreApplication.translate("searchform", u"24:00", None))

        self.label_29.setText(QCoreApplication.translate("searchform", u"Arr. time from:", None))
        self.atime_from.setItemText(0, "")
        self.atime_from.setItemText(1, QCoreApplication.translate("searchform", u"00:00", None))
        self.atime_from.setItemText(2, QCoreApplication.translate("searchform", u"01:00", None))
        self.atime_from.setItemText(3, QCoreApplication.translate("searchform", u"02:00", None))
        self.atime_from.setItemText(4, QCoreApplication.translate("searchform", u"03:00", None))
        self.atime_from.setItemText(5, QCoreApplication.translate("searchform", u"04:00", None))
        self.atime_from.setItemText(6, QCoreApplication.translate("searchform", u"05:00", None))
        self.atime_from.setItemText(7, QCoreApplication.translate("searchform", u"06:00", None))
        self.atime_from.setItemText(8, QCoreApplication.translate("searchform", u"07:00", None))
        self.atime_from.setItemText(9, QCoreApplication.translate("searchform", u"08:00", None))
        self.atime_from.setItemText(10, QCoreApplication.translate("searchform", u"09:00", None))
        self.atime_from.setItemText(11, QCoreApplication.translate("searchform", u"10:00", None))
        self.atime_from.setItemText(12, QCoreApplication.translate("searchform", u"11:00", None))
        self.atime_from.setItemText(13, QCoreApplication.translate("searchform", u"12:00", None))
        self.atime_from.setItemText(14, QCoreApplication.translate("searchform", u"13:00", None))
        self.atime_from.setItemText(15, QCoreApplication.translate("searchform", u"14:00", None))
        self.atime_from.setItemText(16, QCoreApplication.translate("searchform", u"15:00", None))
        self.atime_from.setItemText(17, QCoreApplication.translate("searchform", u"16:00", None))
        self.atime_from.setItemText(18, QCoreApplication.translate("searchform", u"17:00", None))
        self.atime_from.setItemText(19, QCoreApplication.translate("searchform", u"18:00", None))
        self.atime_from.setItemText(20, QCoreApplication.translate("searchform", u"19:00", None))
        self.atime_from.setItemText(21, QCoreApplication.translate("searchform", u"20:00", None))
        self.atime_from.setItemText(22, QCoreApplication.translate("searchform", u"21:00", None))
        self.atime_from.setItemText(23, QCoreApplication.translate("searchform", u"22:00", None))
        self.atime_from.setItemText(24, QCoreApplication.translate("searchform", u"23:00", None))
        self.atime_from.setItemText(25, QCoreApplication.translate("searchform", u"24:00", None))

        self.label_30.setText(QCoreApplication.translate("searchform", u"Arr. time to:", None))
        self.atime_to.setItemText(0, "")
        self.atime_to.setItemText(1, QCoreApplication.translate("searchform", u"00:00", None))
        self.atime_to.setItemText(2, QCoreApplication.translate("searchform", u"01:00", None))
        self.atime_to.setItemText(3, QCoreApplication.translate("searchform", u"02:00", None))
        self.atime_to.setItemText(4, QCoreApplication.translate("searchform", u"03:00", None))
        self.atime_to.setItemText(5, QCoreApplication.translate("searchform", u"04:00", None))
        self.atime_to.setItemText(6, QCoreApplication.translate("searchform", u"05:00", None))
        self.atime_to.setItemText(7, QCoreApplication.translate("searchform", u"06:00", None))
        self.atime_to.setItemText(8, QCoreApplication.translate("searchform", u"07:00", None))
        self.atime_to.setItemText(9, QCoreApplication.translate("searchform", u"08:00", None))
        self.atime_to.setItemText(10, QCoreApplication.translate("searchform", u"09:00", None))
        self.atime_to.setItemText(11, QCoreApplication.translate("searchform", u"10:00", None))
        self.atime_to.setItemText(12, QCoreApplication.translate("searchform", u"11:00", None))
        self.atime_to.setItemText(13, QCoreApplication.translate("searchform", u"12:00", None))
        self.atime_to.setItemText(14, QCoreApplication.translate("searchform", u"13:00", None))
        self.atime_to.setItemText(15, QCoreApplication.translate("searchform", u"14:00", None))
        self.atime_to.setItemText(16, QCoreApplication.translate("searchform", u"15:00", None))
        self.atime_to.setItemText(17, QCoreApplication.translate("searchform", u"16:00", None))
        self.atime_to.setItemText(18, QCoreApplication.translate("searchform", u"17:00", None))
        self.atime_to.setItemText(19, QCoreApplication.translate("searchform", u"18:00", None))
        self.atime_to.setItemText(20, QCoreApplication.translate("searchform", u"19:00", None))
        self.atime_to.setItemText(21, QCoreApplication.translate("searchform", u"20:00", None))
        self.atime_to.setItemText(22, QCoreApplication.translate("searchform", u"21:00", None))
        self.atime_to.setItemText(23, QCoreApplication.translate("searchform", u"22:00", None))
        self.atime_to.setItemText(24, QCoreApplication.translate("searchform", u"23:00", None))
        self.atime_to.setItemText(25, QCoreApplication.translate("searchform", u"24:00", None))

        self.label_32.setText(QCoreApplication.translate("searchform", u"Ret dep. time from:", None))
        self.ret_dtime_from.setItemText(0, "")
        self.ret_dtime_from.setItemText(1, QCoreApplication.translate("searchform", u"00:00", None))
        self.ret_dtime_from.setItemText(2, QCoreApplication.translate("searchform", u"01:00", None))
        self.ret_dtime_from.setItemText(3, QCoreApplication.translate("searchform", u"02:00", None))
        self.ret_dtime_from.setItemText(4, QCoreApplication.translate("searchform", u"03:00", None))
        self.ret_dtime_from.setItemText(5, QCoreApplication.translate("searchform", u"04:00", None))
        self.ret_dtime_from.setItemText(6, QCoreApplication.translate("searchform", u"05:00", None))
        self.ret_dtime_from.setItemText(7, QCoreApplication.translate("searchform", u"06:00", None))
        self.ret_dtime_from.setItemText(8, QCoreApplication.translate("searchform", u"07:00", None))
        self.ret_dtime_from.setItemText(9, QCoreApplication.translate("searchform", u"08:00", None))
        self.ret_dtime_from.setItemText(10, QCoreApplication.translate("searchform", u"09:00", None))
        self.ret_dtime_from.setItemText(11, QCoreApplication.translate("searchform", u"10:00", None))
        self.ret_dtime_from.setItemText(12, QCoreApplication.translate("searchform", u"11:00", None))
        self.ret_dtime_from.setItemText(13, QCoreApplication.translate("searchform", u"12:00", None))
        self.ret_dtime_from.setItemText(14, QCoreApplication.translate("searchform", u"13:00", None))
        self.ret_dtime_from.setItemText(15, QCoreApplication.translate("searchform", u"14:00", None))
        self.ret_dtime_from.setItemText(16, QCoreApplication.translate("searchform", u"15:00", None))
        self.ret_dtime_from.setItemText(17, QCoreApplication.translate("searchform", u"16:00", None))
        self.ret_dtime_from.setItemText(18, QCoreApplication.translate("searchform", u"17:00", None))
        self.ret_dtime_from.setItemText(19, QCoreApplication.translate("searchform", u"18:00", None))
        self.ret_dtime_from.setItemText(20, QCoreApplication.translate("searchform", u"19:00", None))
        self.ret_dtime_from.setItemText(21, QCoreApplication.translate("searchform", u"20:00", None))
        self.ret_dtime_from.setItemText(22, QCoreApplication.translate("searchform", u"21:00", None))
        self.ret_dtime_from.setItemText(23, QCoreApplication.translate("searchform", u"22:00", None))
        self.ret_dtime_from.setItemText(24, QCoreApplication.translate("searchform", u"23:00", None))
        self.ret_dtime_from.setItemText(25, QCoreApplication.translate("searchform", u"24:00", None))

        self.label_31.setText(QCoreApplication.translate("searchform", u"Ret. dep. time to:", None))
        self.ret_dtime_to.setItemText(0, "")
        self.ret_dtime_to.setItemText(1, QCoreApplication.translate("searchform", u"00:00", None))
        self.ret_dtime_to.setItemText(2, QCoreApplication.translate("searchform", u"01:00", None))
        self.ret_dtime_to.setItemText(3, QCoreApplication.translate("searchform", u"02:00", None))
        self.ret_dtime_to.setItemText(4, QCoreApplication.translate("searchform", u"03:00", None))
        self.ret_dtime_to.setItemText(5, QCoreApplication.translate("searchform", u"04:00", None))
        self.ret_dtime_to.setItemText(6, QCoreApplication.translate("searchform", u"05:00", None))
        self.ret_dtime_to.setItemText(7, QCoreApplication.translate("searchform", u"06:00", None))
        self.ret_dtime_to.setItemText(8, QCoreApplication.translate("searchform", u"07:00", None))
        self.ret_dtime_to.setItemText(9, QCoreApplication.translate("searchform", u"08:00", None))
        self.ret_dtime_to.setItemText(10, QCoreApplication.translate("searchform", u"09:00", None))
        self.ret_dtime_to.setItemText(11, QCoreApplication.translate("searchform", u"10:00", None))
        self.ret_dtime_to.setItemText(12, QCoreApplication.translate("searchform", u"11:00", None))
        self.ret_dtime_to.setItemText(13, QCoreApplication.translate("searchform", u"12:00", None))
        self.ret_dtime_to.setItemText(14, QCoreApplication.translate("searchform", u"13:00", None))
        self.ret_dtime_to.setItemText(15, QCoreApplication.translate("searchform", u"14:00", None))
        self.ret_dtime_to.setItemText(16, QCoreApplication.translate("searchform", u"15:00", None))
        self.ret_dtime_to.setItemText(17, QCoreApplication.translate("searchform", u"16:00", None))
        self.ret_dtime_to.setItemText(18, QCoreApplication.translate("searchform", u"17:00", None))
        self.ret_dtime_to.setItemText(19, QCoreApplication.translate("searchform", u"18:00", None))
        self.ret_dtime_to.setItemText(20, QCoreApplication.translate("searchform", u"19:00", None))
        self.ret_dtime_to.setItemText(21, QCoreApplication.translate("searchform", u"20:00", None))
        self.ret_dtime_to.setItemText(22, QCoreApplication.translate("searchform", u"21:00", None))
        self.ret_dtime_to.setItemText(23, QCoreApplication.translate("searchform", u"22:00", None))
        self.ret_dtime_to.setItemText(24, QCoreApplication.translate("searchform", u"23:00", None))
        self.ret_dtime_to.setItemText(25, QCoreApplication.translate("searchform", u"24:00", None))

        self.label_33.setText(QCoreApplication.translate("searchform", u"Ret. arr. time from:", None))
        self.ret_atime_from.setItemText(0, "")
        self.ret_atime_from.setItemText(1, QCoreApplication.translate("searchform", u"00:00", None))
        self.ret_atime_from.setItemText(2, QCoreApplication.translate("searchform", u"01:00", None))
        self.ret_atime_from.setItemText(3, QCoreApplication.translate("searchform", u"02:00", None))
        self.ret_atime_from.setItemText(4, QCoreApplication.translate("searchform", u"03:00", None))
        self.ret_atime_from.setItemText(5, QCoreApplication.translate("searchform", u"04:00", None))
        self.ret_atime_from.setItemText(6, QCoreApplication.translate("searchform", u"05:00", None))
        self.ret_atime_from.setItemText(7, QCoreApplication.translate("searchform", u"06:00", None))
        self.ret_atime_from.setItemText(8, QCoreApplication.translate("searchform", u"07:00", None))
        self.ret_atime_from.setItemText(9, QCoreApplication.translate("searchform", u"08:00", None))
        self.ret_atime_from.setItemText(10, QCoreApplication.translate("searchform", u"09:00", None))
        self.ret_atime_from.setItemText(11, QCoreApplication.translate("searchform", u"10:00", None))
        self.ret_atime_from.setItemText(12, QCoreApplication.translate("searchform", u"11:00", None))
        self.ret_atime_from.setItemText(13, QCoreApplication.translate("searchform", u"12:00", None))
        self.ret_atime_from.setItemText(14, QCoreApplication.translate("searchform", u"13:00", None))
        self.ret_atime_from.setItemText(15, QCoreApplication.translate("searchform", u"14:00", None))
        self.ret_atime_from.setItemText(16, QCoreApplication.translate("searchform", u"15:00", None))
        self.ret_atime_from.setItemText(17, QCoreApplication.translate("searchform", u"16:00", None))
        self.ret_atime_from.setItemText(18, QCoreApplication.translate("searchform", u"17:00", None))
        self.ret_atime_from.setItemText(19, QCoreApplication.translate("searchform", u"18:00", None))
        self.ret_atime_from.setItemText(20, QCoreApplication.translate("searchform", u"19:00", None))
        self.ret_atime_from.setItemText(21, QCoreApplication.translate("searchform", u"20:00", None))
        self.ret_atime_from.setItemText(22, QCoreApplication.translate("searchform", u"21:00", None))
        self.ret_atime_from.setItemText(23, QCoreApplication.translate("searchform", u"22:00", None))
        self.ret_atime_from.setItemText(24, QCoreApplication.translate("searchform", u"23:00", None))
        self.ret_atime_from.setItemText(25, QCoreApplication.translate("searchform", u"24:00", None))

        self.label_34.setText(QCoreApplication.translate("searchform", u"Ret. arr. time to:", None))
        self.ret_atime_to.setItemText(0, "")
        self.ret_atime_to.setItemText(1, QCoreApplication.translate("searchform", u"00:00", None))
        self.ret_atime_to.setItemText(2, QCoreApplication.translate("searchform", u"01:00", None))
        self.ret_atime_to.setItemText(3, QCoreApplication.translate("searchform", u"02:00", None))
        self.ret_atime_to.setItemText(4, QCoreApplication.translate("searchform", u"03:00", None))
        self.ret_atime_to.setItemText(5, QCoreApplication.translate("searchform", u"04:00", None))
        self.ret_atime_to.setItemText(6, QCoreApplication.translate("searchform", u"05:00", None))
        self.ret_atime_to.setItemText(7, QCoreApplication.translate("searchform", u"06:00", None))
        self.ret_atime_to.setItemText(8, QCoreApplication.translate("searchform", u"07:00", None))
        self.ret_atime_to.setItemText(9, QCoreApplication.translate("searchform", u"08:00", None))
        self.ret_atime_to.setItemText(10, QCoreApplication.translate("searchform", u"09:00", None))
        self.ret_atime_to.setItemText(11, QCoreApplication.translate("searchform", u"10:00", None))
        self.ret_atime_to.setItemText(12, QCoreApplication.translate("searchform", u"11:00", None))
        self.ret_atime_to.setItemText(13, QCoreApplication.translate("searchform", u"12:00", None))
        self.ret_atime_to.setItemText(14, QCoreApplication.translate("searchform", u"13:00", None))
        self.ret_atime_to.setItemText(15, QCoreApplication.translate("searchform", u"14:00", None))
        self.ret_atime_to.setItemText(16, QCoreApplication.translate("searchform", u"15:00", None))
        self.ret_atime_to.setItemText(17, QCoreApplication.translate("searchform", u"16:00", None))
        self.ret_atime_to.setItemText(18, QCoreApplication.translate("searchform", u"17:00", None))
        self.ret_atime_to.setItemText(19, QCoreApplication.translate("searchform", u"18:00", None))
        self.ret_atime_to.setItemText(20, QCoreApplication.translate("searchform", u"19:00", None))
        self.ret_atime_to.setItemText(21, QCoreApplication.translate("searchform", u"20:00", None))
        self.ret_atime_to.setItemText(22, QCoreApplication.translate("searchform", u"21:00", None))
        self.ret_atime_to.setItemText(23, QCoreApplication.translate("searchform", u"22:00", None))
        self.ret_atime_to.setItemText(24, QCoreApplication.translate("searchform", u"23:00", None))
        self.ret_atime_to.setItemText(25, QCoreApplication.translate("searchform", u"24:00", None))

        self.label_35.setText(QCoreApplication.translate("searchform", u"Stoppver from:", None))
        self.label_36.setText(QCoreApplication.translate("searchform", u"Stopover to:", None))
        self.label_37.setText(QCoreApplication.translate("searchform", u"Max stopover:", None))
        self.label_38.setText(QCoreApplication.translate("searchform", u"Max sector stopovers", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("searchform", u"Time and stopovers", None))
        self.label_39.setText(QCoreApplication.translate("searchform", u"Currency:", None))
        self.currency.setItemText(0, "")
        self.currency.setItemText(1, QCoreApplication.translate("searchform", u"AED", None))
        self.currency.setItemText(2, QCoreApplication.translate("searchform", u"AFN", None))
        self.currency.setItemText(3, QCoreApplication.translate("searchform", u"ALL", None))
        self.currency.setItemText(4, QCoreApplication.translate("searchform", u"AMD", None))
        self.currency.setItemText(5, QCoreApplication.translate("searchform", u"ANG", None))
        self.currency.setItemText(6, QCoreApplication.translate("searchform", u"AOA", None))
        self.currency.setItemText(7, QCoreApplication.translate("searchform", u"ARS", None))
        self.currency.setItemText(8, QCoreApplication.translate("searchform", u"AUD", None))
        self.currency.setItemText(9, QCoreApplication.translate("searchform", u"AWG", None))
        self.currency.setItemText(10, QCoreApplication.translate("searchform", u"AZN", None))
        self.currency.setItemText(11, QCoreApplication.translate("searchform", u"BAM", None))
        self.currency.setItemText(12, QCoreApplication.translate("searchform", u"BBD", None))
        self.currency.setItemText(13, QCoreApplication.translate("searchform", u"BDT", None))
        self.currency.setItemText(14, QCoreApplication.translate("searchform", u"BGN", None))
        self.currency.setItemText(15, QCoreApplication.translate("searchform", u"BHD", None))
        self.currency.setItemText(16, QCoreApplication.translate("searchform", u"BIF", None))
        self.currency.setItemText(17, QCoreApplication.translate("searchform", u"BMD", None))
        self.currency.setItemText(18, QCoreApplication.translate("searchform", u"BND", None))
        self.currency.setItemText(19, QCoreApplication.translate("searchform", u"BOB", None))
        self.currency.setItemText(20, QCoreApplication.translate("searchform", u"BRL", None))
        self.currency.setItemText(21, QCoreApplication.translate("searchform", u"BSD", None))
        self.currency.setItemText(22, QCoreApplication.translate("searchform", u"BTC", None))
        self.currency.setItemText(23, QCoreApplication.translate("searchform", u"BTN", None))
        self.currency.setItemText(24, QCoreApplication.translate("searchform", u"BWP", None))
        self.currency.setItemText(25, QCoreApplication.translate("searchform", u"BYN", None))
        self.currency.setItemText(26, QCoreApplication.translate("searchform", u"BZD", None))
        self.currency.setItemText(27, QCoreApplication.translate("searchform", u"CAD", None))
        self.currency.setItemText(28, QCoreApplication.translate("searchform", u"CDF", None))
        self.currency.setItemText(29, QCoreApplication.translate("searchform", u"CHF", None))
        self.currency.setItemText(30, QCoreApplication.translate("searchform", u"CLF", None))
        self.currency.setItemText(31, QCoreApplication.translate("searchform", u"CLP", None))
        self.currency.setItemText(32, QCoreApplication.translate("searchform", u"CNY", None))
        self.currency.setItemText(33, QCoreApplication.translate("searchform", u"COP", None))
        self.currency.setItemText(34, QCoreApplication.translate("searchform", u"CRC", None))
        self.currency.setItemText(35, QCoreApplication.translate("searchform", u"CUC", None))
        self.currency.setItemText(36, QCoreApplication.translate("searchform", u"CUP", None))
        self.currency.setItemText(37, QCoreApplication.translate("searchform", u"CVE", None))
        self.currency.setItemText(38, QCoreApplication.translate("searchform", u"CZK", None))
        self.currency.setItemText(39, QCoreApplication.translate("searchform", u"DJF", None))
        self.currency.setItemText(40, QCoreApplication.translate("searchform", u"DKK", None))
        self.currency.setItemText(41, QCoreApplication.translate("searchform", u"DOP", None))
        self.currency.setItemText(42, QCoreApplication.translate("searchform", u"DZD", None))
        self.currency.setItemText(43, QCoreApplication.translate("searchform", u"EEK", None))
        self.currency.setItemText(44, QCoreApplication.translate("searchform", u"EGP", None))
        self.currency.setItemText(45, QCoreApplication.translate("searchform", u"ERN", None))
        self.currency.setItemText(46, QCoreApplication.translate("searchform", u"ETB", None))
        self.currency.setItemText(47, QCoreApplication.translate("searchform", u"EUR", None))
        self.currency.setItemText(48, QCoreApplication.translate("searchform", u"FJD", None))
        self.currency.setItemText(49, QCoreApplication.translate("searchform", u"FKP", None))
        self.currency.setItemText(50, QCoreApplication.translate("searchform", u"GBP", None))
        self.currency.setItemText(51, QCoreApplication.translate("searchform", u"GEL", None))
        self.currency.setItemText(52, QCoreApplication.translate("searchform", u"GGP", None))
        self.currency.setItemText(53, QCoreApplication.translate("searchform", u"GHS", None))
        self.currency.setItemText(54, QCoreApplication.translate("searchform", u"GIP", None))
        self.currency.setItemText(55, QCoreApplication.translate("searchform", u"GMD", None))
        self.currency.setItemText(56, QCoreApplication.translate("searchform", u"GNF", None))
        self.currency.setItemText(57, QCoreApplication.translate("searchform", u"GTQ", None))
        self.currency.setItemText(58, QCoreApplication.translate("searchform", u"GYD", None))
        self.currency.setItemText(59, QCoreApplication.translate("searchform", u"HKD", None))
        self.currency.setItemText(60, QCoreApplication.translate("searchform", u"HNL", None))
        self.currency.setItemText(61, QCoreApplication.translate("searchform", u"HRK", None))
        self.currency.setItemText(62, QCoreApplication.translate("searchform", u"HTG", None))
        self.currency.setItemText(63, QCoreApplication.translate("searchform", u"HUF", None))
        self.currency.setItemText(64, QCoreApplication.translate("searchform", u"IDR", None))
        self.currency.setItemText(65, QCoreApplication.translate("searchform", u"ILS", None))
        self.currency.setItemText(66, QCoreApplication.translate("searchform", u"IMP", None))
        self.currency.setItemText(67, QCoreApplication.translate("searchform", u"INR", None))
        self.currency.setItemText(68, QCoreApplication.translate("searchform", u"IQD", None))
        self.currency.setItemText(69, QCoreApplication.translate("searchform", u"IRR", None))
        self.currency.setItemText(70, QCoreApplication.translate("searchform", u"ISK", None))
        self.currency.setItemText(71, QCoreApplication.translate("searchform", u"JEP", None))
        self.currency.setItemText(72, QCoreApplication.translate("searchform", u"JMD", None))
        self.currency.setItemText(73, QCoreApplication.translate("searchform", u"JOD", None))
        self.currency.setItemText(74, QCoreApplication.translate("searchform", u"JPY", None))
        self.currency.setItemText(75, QCoreApplication.translate("searchform", u"KES", None))
        self.currency.setItemText(76, QCoreApplication.translate("searchform", u"KGS", None))
        self.currency.setItemText(77, QCoreApplication.translate("searchform", u"KHR", None))
        self.currency.setItemText(78, QCoreApplication.translate("searchform", u"KMF", None))
        self.currency.setItemText(79, QCoreApplication.translate("searchform", u"KPW", None))
        self.currency.setItemText(80, QCoreApplication.translate("searchform", u"KRW", None))
        self.currency.setItemText(81, QCoreApplication.translate("searchform", u"KWD", None))
        self.currency.setItemText(82, QCoreApplication.translate("searchform", u"KYD", None))
        self.currency.setItemText(83, QCoreApplication.translate("searchform", u"KZT", None))
        self.currency.setItemText(84, QCoreApplication.translate("searchform", u"LAK", None))
        self.currency.setItemText(85, QCoreApplication.translate("searchform", u"LBP", None))
        self.currency.setItemText(86, QCoreApplication.translate("searchform", u"LKR", None))
        self.currency.setItemText(87, QCoreApplication.translate("searchform", u"LRD", None))
        self.currency.setItemText(88, QCoreApplication.translate("searchform", u"LSL", None))
        self.currency.setItemText(89, QCoreApplication.translate("searchform", u"LTL", None))
        self.currency.setItemText(90, QCoreApplication.translate("searchform", u"LVL", None))
        self.currency.setItemText(91, QCoreApplication.translate("searchform", u"LYD", None))
        self.currency.setItemText(92, QCoreApplication.translate("searchform", u"MAD", None))
        self.currency.setItemText(93, QCoreApplication.translate("searchform", u"MDL", None))
        self.currency.setItemText(94, QCoreApplication.translate("searchform", u"MGA", None))
        self.currency.setItemText(95, QCoreApplication.translate("searchform", u"MKD", None))
        self.currency.setItemText(96, QCoreApplication.translate("searchform", u"MMK", None))
        self.currency.setItemText(97, QCoreApplication.translate("searchform", u"MNT", None))
        self.currency.setItemText(98, QCoreApplication.translate("searchform", u"MOP", None))
        self.currency.setItemText(99, QCoreApplication.translate("searchform", u"MRO", None))
        self.currency.setItemText(100, QCoreApplication.translate("searchform", u"MTL", None))
        self.currency.setItemText(101, QCoreApplication.translate("searchform", u"MUR", None))
        self.currency.setItemText(102, QCoreApplication.translate("searchform", u"MVR", None))
        self.currency.setItemText(103, QCoreApplication.translate("searchform", u"MWK", None))
        self.currency.setItemText(104, QCoreApplication.translate("searchform", u"MXN", None))
        self.currency.setItemText(105, QCoreApplication.translate("searchform", u"MYR", None))
        self.currency.setItemText(106, QCoreApplication.translate("searchform", u"MZN", None))
        self.currency.setItemText(107, QCoreApplication.translate("searchform", u"NAD", None))
        self.currency.setItemText(108, QCoreApplication.translate("searchform", u"NGN", None))
        self.currency.setItemText(109, QCoreApplication.translate("searchform", u"NIO", None))
        self.currency.setItemText(110, QCoreApplication.translate("searchform", u"NOK", None))
        self.currency.setItemText(111, QCoreApplication.translate("searchform", u"NPR", None))
        self.currency.setItemText(112, QCoreApplication.translate("searchform", u"NZD", None))
        self.currency.setItemText(113, QCoreApplication.translate("searchform", u"OMR", None))
        self.currency.setItemText(114, QCoreApplication.translate("searchform", u"PAB", None))
        self.currency.setItemText(115, QCoreApplication.translate("searchform", u"PEN", None))
        self.currency.setItemText(116, QCoreApplication.translate("searchform", u"PGK", None))
        self.currency.setItemText(117, QCoreApplication.translate("searchform", u"PHP", None))
        self.currency.setItemText(118, QCoreApplication.translate("searchform", u"PKR", None))
        self.currency.setItemText(119, QCoreApplication.translate("searchform", u"PLN", None))
        self.currency.setItemText(120, QCoreApplication.translate("searchform", u"PYG", None))
        self.currency.setItemText(121, QCoreApplication.translate("searchform", u"QAR", None))
        self.currency.setItemText(122, QCoreApplication.translate("searchform", u"QUN", None))
        self.currency.setItemText(123, QCoreApplication.translate("searchform", u"RON", None))
        self.currency.setItemText(124, QCoreApplication.translate("searchform", u"RSD", None))
        self.currency.setItemText(125, QCoreApplication.translate("searchform", u"RUB", None))
        self.currency.setItemText(126, QCoreApplication.translate("searchform", u"RWF", None))
        self.currency.setItemText(127, QCoreApplication.translate("searchform", u"SAR", None))
        self.currency.setItemText(128, QCoreApplication.translate("searchform", u"SBD", None))
        self.currency.setItemText(129, QCoreApplication.translate("searchform", u"SCR", None))
        self.currency.setItemText(130, QCoreApplication.translate("searchform", u"SDG", None))
        self.currency.setItemText(131, QCoreApplication.translate("searchform", u"SEK", None))
        self.currency.setItemText(132, QCoreApplication.translate("searchform", u"SGD", None))
        self.currency.setItemText(133, QCoreApplication.translate("searchform", u"SHP", None))
        self.currency.setItemText(134, QCoreApplication.translate("searchform", u"SLL", None))
        self.currency.setItemText(135, QCoreApplication.translate("searchform", u"SOS", None))
        self.currency.setItemText(136, QCoreApplication.translate("searchform", u"SRD", None))
        self.currency.setItemText(137, QCoreApplication.translate("searchform", u"STD", None))
        self.currency.setItemText(138, QCoreApplication.translate("searchform", u"SVC", None))
        self.currency.setItemText(139, QCoreApplication.translate("searchform", u"SYP", None))
        self.currency.setItemText(140, QCoreApplication.translate("searchform", u"SZL", None))
        self.currency.setItemText(141, QCoreApplication.translate("searchform", u"THB", None))
        self.currency.setItemText(142, QCoreApplication.translate("searchform", u"TJS", None))
        self.currency.setItemText(143, QCoreApplication.translate("searchform", u"TMT", None))
        self.currency.setItemText(144, QCoreApplication.translate("searchform", u"TND", None))
        self.currency.setItemText(145, QCoreApplication.translate("searchform", u"TOP", None))
        self.currency.setItemText(146, QCoreApplication.translate("searchform", u"TRY", None))
        self.currency.setItemText(147, QCoreApplication.translate("searchform", u"TTD", None))
        self.currency.setItemText(148, QCoreApplication.translate("searchform", u"TWD", None))
        self.currency.setItemText(149, QCoreApplication.translate("searchform", u"TZS", None))
        self.currency.setItemText(150, QCoreApplication.translate("searchform", u"UAH", None))
        self.currency.setItemText(151, QCoreApplication.translate("searchform", u"UGX", None))
        self.currency.setItemText(152, QCoreApplication.translate("searchform", u"USD", None))
        self.currency.setItemText(153, QCoreApplication.translate("searchform", u"UYU", None))
        self.currency.setItemText(154, QCoreApplication.translate("searchform", u"UZS", None))
        self.currency.setItemText(155, QCoreApplication.translate("searchform", u"VEF", None))
        self.currency.setItemText(156, QCoreApplication.translate("searchform", u"VND", None))
        self.currency.setItemText(157, QCoreApplication.translate("searchform", u"VUV", None))
        self.currency.setItemText(158, QCoreApplication.translate("searchform", u"WST", None))
        self.currency.setItemText(159, QCoreApplication.translate("searchform", u"XAF", None))
        self.currency.setItemText(160, QCoreApplication.translate("searchform", u"XCD", None))
        self.currency.setItemText(161, QCoreApplication.translate("searchform", u"XOF", None))
        self.currency.setItemText(162, QCoreApplication.translate("searchform", u"XPF", None))
        self.currency.setItemText(163, QCoreApplication.translate("searchform", u"YER", None))
        self.currency.setItemText(164, QCoreApplication.translate("searchform", u"ZAR", None))
        self.currency.setItemText(165, QCoreApplication.translate("searchform", u"ZMK", None))
        self.currency.setItemText(166, QCoreApplication.translate("searchform", u"ZMW", None))
        self.currency.setItemText(167, QCoreApplication.translate("searchform", u"ZWL", None))

        self.currency.setCurrentText(QCoreApplication.translate("searchform", u"HUF", None))
        self.label_40.setText(QCoreApplication.translate("searchform", u"Locale:", None))
        self.locale.setItemText(0, QCoreApplication.translate("searchform", u"ae", None))
        self.locale.setItemText(1, QCoreApplication.translate("searchform", u"ag", None))
        self.locale.setItemText(2, QCoreApplication.translate("searchform", u"ar", None))
        self.locale.setItemText(3, QCoreApplication.translate("searchform", u"at", None))
        self.locale.setItemText(4, QCoreApplication.translate("searchform", u"au", None))
        self.locale.setItemText(5, QCoreApplication.translate("searchform", u"be", None))
        self.locale.setItemText(6, QCoreApplication.translate("searchform", u"bg", None))
        self.locale.setItemText(7, QCoreApplication.translate("searchform", u"bh", None))
        self.locale.setItemText(8, QCoreApplication.translate("searchform", u"br", None))
        self.locale.setItemText(9, QCoreApplication.translate("searchform", u"by", None))
        self.locale.setItemText(10, QCoreApplication.translate("searchform", u"ca", None))
        self.locale.setItemText(11, QCoreApplication.translate("searchform", u"ca-fr", None))
        self.locale.setItemText(12, QCoreApplication.translate("searchform", u"ch", None))
        self.locale.setItemText(13, QCoreApplication.translate("searchform", u"cl", None))
        self.locale.setItemText(14, QCoreApplication.translate("searchform", u"cn", None))
        self.locale.setItemText(15, QCoreApplication.translate("searchform", u"co", None))
        self.locale.setItemText(16, QCoreApplication.translate("searchform", u"ct", None))
        self.locale.setItemText(17, QCoreApplication.translate("searchform", u"cz", None))
        self.locale.setItemText(18, QCoreApplication.translate("searchform", u"da", None))
        self.locale.setItemText(19, QCoreApplication.translate("searchform", u"de", None))
        self.locale.setItemText(20, QCoreApplication.translate("searchform", u"dk", None))
        self.locale.setItemText(21, QCoreApplication.translate("searchform", u"ec", None))
        self.locale.setItemText(22, QCoreApplication.translate("searchform", u"ee", None))
        self.locale.setItemText(23, QCoreApplication.translate("searchform", u"el", None))
        self.locale.setItemText(24, QCoreApplication.translate("searchform", u"en", None))
        self.locale.setItemText(25, QCoreApplication.translate("searchform", u"es", None))
        self.locale.setItemText(26, QCoreApplication.translate("searchform", u"fi", None))
        self.locale.setItemText(27, QCoreApplication.translate("searchform", u"fr", None))
        self.locale.setItemText(28, QCoreApplication.translate("searchform", u"gb", None))
        self.locale.setItemText(29, QCoreApplication.translate("searchform", u"gr", None))
        self.locale.setItemText(30, QCoreApplication.translate("searchform", u"hk", None))
        self.locale.setItemText(31, QCoreApplication.translate("searchform", u"hr", None))
        self.locale.setItemText(32, QCoreApplication.translate("searchform", u"hu", None))
        self.locale.setItemText(33, QCoreApplication.translate("searchform", u"id", None))
        self.locale.setItemText(34, QCoreApplication.translate("searchform", u"ie", None))
        self.locale.setItemText(35, QCoreApplication.translate("searchform", u"il", None))
        self.locale.setItemText(36, QCoreApplication.translate("searchform", u"in", None))
        self.locale.setItemText(37, QCoreApplication.translate("searchform", u"is", None))
        self.locale.setItemText(38, QCoreApplication.translate("searchform", u"it", None))
        self.locale.setItemText(39, QCoreApplication.translate("searchform", u"ja", None))
        self.locale.setItemText(40, QCoreApplication.translate("searchform", u"jo", None))
        self.locale.setItemText(41, QCoreApplication.translate("searchform", u"jp", None))
        self.locale.setItemText(42, QCoreApplication.translate("searchform", u"ko", None))
        self.locale.setItemText(43, QCoreApplication.translate("searchform", u"kr", None))
        self.locale.setItemText(44, QCoreApplication.translate("searchform", u"kw", None))
        self.locale.setItemText(45, QCoreApplication.translate("searchform", u"kz", None))
        self.locale.setItemText(46, QCoreApplication.translate("searchform", u"lt", None))
        self.locale.setItemText(47, QCoreApplication.translate("searchform", u"mx", None))
        self.locale.setItemText(48, QCoreApplication.translate("searchform", u"my", None))
        self.locale.setItemText(49, QCoreApplication.translate("searchform", u"nl", None))
        self.locale.setItemText(50, QCoreApplication.translate("searchform", u"no", None))
        self.locale.setItemText(51, QCoreApplication.translate("searchform", u"nz", None))
        self.locale.setItemText(52, QCoreApplication.translate("searchform", u"om", None))
        self.locale.setItemText(53, QCoreApplication.translate("searchform", u"pe", None))
        self.locale.setItemText(54, QCoreApplication.translate("searchform", u"ph", None))
        self.locale.setItemText(55, QCoreApplication.translate("searchform", u"pl", None))
        self.locale.setItemText(56, QCoreApplication.translate("searchform", u"pt", None))
        self.locale.setItemText(57, QCoreApplication.translate("searchform", u"qa", None))
        self.locale.setItemText(58, QCoreApplication.translate("searchform", u"ro", None))
        self.locale.setItemText(59, QCoreApplication.translate("searchform", u"rs", None))
        self.locale.setItemText(60, QCoreApplication.translate("searchform", u"ru", None))
        self.locale.setItemText(61, QCoreApplication.translate("searchform", u"sa", None))
        self.locale.setItemText(62, QCoreApplication.translate("searchform", u"se", None))
        self.locale.setItemText(63, QCoreApplication.translate("searchform", u"sg", None))
        self.locale.setItemText(64, QCoreApplication.translate("searchform", u"sk", None))
        self.locale.setItemText(65, QCoreApplication.translate("searchform", u"sr", None))
        self.locale.setItemText(66, QCoreApplication.translate("searchform", u"sv", None))
        self.locale.setItemText(67, QCoreApplication.translate("searchform", u"th", None))
        self.locale.setItemText(68, QCoreApplication.translate("searchform", u"tr", None))
        self.locale.setItemText(69, QCoreApplication.translate("searchform", u"tw", None))
        self.locale.setItemText(70, QCoreApplication.translate("searchform", u"ua", None))
        self.locale.setItemText(71, QCoreApplication.translate("searchform", u"uk", None))
        self.locale.setItemText(72, QCoreApplication.translate("searchform", u"us", None))
        self.locale.setItemText(73, QCoreApplication.translate("searchform", u"vn", None))
        self.locale.setItemText(74, QCoreApplication.translate("searchform", u"za", None))

        self.locale.setCurrentText(QCoreApplication.translate("searchform", u"hu", None))
        self.label_41.setText(QCoreApplication.translate("searchform", u"Partner market", None))
        self.label_42.setText(QCoreApplication.translate("searchform", u"Vehicle type:", None))
        self.vehicle_type.setItemText(0, "")
        self.vehicle_type.setItemText(1, QCoreApplication.translate("searchform", u"aircraft", None))
        self.vehicle_type.setItemText(2, QCoreApplication.translate("searchform", u"bus", None))
        self.vehicle_type.setItemText(3, QCoreApplication.translate("searchform", u"train", None))

        self.conn_on_diff_airport.setText(QCoreApplication.translate("searchform", u"Conn on diff airport", None))
        self.ret_to_diff_city.setText(QCoreApplication.translate("searchform", u"Ret to diff city", None))
        self.one_per_date.setText(QCoreApplication.translate("searchform", u"One per date", None))
        self.ret_from_diff_airport.setText(QCoreApplication.translate("searchform", u"Ret from diff airport", None))
        self.ret_from_diff_city.setText(QCoreApplication.translate("searchform", u"Ret from diff city", None))
        self.ret_to_diff_airport.setText(QCoreApplication.translate("searchform", u"Ret to diff airport", None))
        self.enable_vi.setText(QCoreApplication.translate("searchform", u"Enable VI", None))
        self.one_for_city.setText(QCoreApplication.translate("searchform", u"One for city", None))
        self.only_weekends.setText(QCoreApplication.translate("searchform", u"Only weekends", None))
        self.only_working_days.setText(QCoreApplication.translate("searchform", u"Only working days", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("searchform", u"Options", None))
    # retranslateUi

